services:
  - type: web
    name: ainaappfrontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: "build"
    routes:
      - src: "/.*"
        dest: "/index.html"
